x = 'hello world'                                #str
x = 1                                            #int
x = 1.5                                          #float
x = 1j                                           #complex 
x = ["apple", "banana", "watermelon"]            #list
x = ("apple", "banana", "watermelon")            #tuple
x = range(5)                                     #range
x = {"name": "archit", "age":25}                 #dictionary (dict)
x = {"apple", "banana", "watermelon"}            #set
x = frozenset({"apple", "banana", "watermelon"}) #frozenset
x = True                                         #Boolean (bool)
x = b"hello"                                     #bytes
x = bytearray(5)                                 #bytearray
x = memoryview(bytes(5))                         #memoryview

a = "Text string"
a = 5
a = 1.5
a = 1j
a = ['first', 'second', 'third']
a = ('apple', 'cherry', 'banana')
a = range(10)
a = { 'a' : 1, 'b' : 2}
a = { 'eraser', 'pencil', 'glass'}
a = frozenset({"bottle", "phone"})
a = True
a = b"Dhwani"
a = bytearray(22)
a = memoryview(bytes(3))
a = None